cargo-features = ["multiple-build-scripts"]

[package]
name = "multiple-build-scripts-test-repo"
version = "0.1.0"
edition = "2024"
build = [ "build3.rs", "build2.rs"]

[dependencies]

[build-dependencies]
cc = "1.2.16"
